version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: atelier_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ateliervelo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: atelier_redis
    ports:
      - "6379:6379"

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: atelier_keycloak
    command: start-dev --http-port=8080 --hostname-strict=false
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata:
